CREATE TABLE IF NOT EXISTS orders (
    id VARCHAR(20) PRIMARY KEY,
    order_number VARCHAR(30) NOT NULL UNIQUE,
    user_id VARCHAR(20) DEFAULT NULL,
    session_token VARCHAR(100) DEFAULT NULL,
    customer_name VARCHAR(100) NOT NULL,
    customer_phone VARCHAR(20) NOT NULL,
    fulfillment_method ENUM('pickup', 'delivery') NOT NULL,
    pickup_date DATE DEFAULT NULL,
    pickup_time TIME DEFAULT NULL,
    delivery_address TEXT,
    address_note VARCHAR(120) DEFAULT '',
    payment_method ENUM('cash', 'qris') NOT NULL,
    payment_status ENUM('pending', 'paid', 'cod') NOT NULL DEFAULT 'pending',
    status ENUM('menunggu konfirmasi', 'diproses', 'siap diambil', 'diantar', 'selesai', 'dibatalkan') NOT NULL DEFAULT 'menunggu konfirmasi',
    notes TEXT,
    total_price INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
    INDEX idx_orders_user (user_id),
    INDEX idx_orders_number (order_number),
    INDEX idx_orders_status (status),
    INDEX idx_orders_session (session_token)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
